#' Convert Protospacer and PAM Coordinates to Absolute Start and Stop Coordinates
#'
#' This function takes calculated protospacer/PAM boundaries and converts them
#' into absolute, 1-based genomic start (minimum) and stop (maximum) coordinates
#' spanning the entire target site (including the full PAM).
#'
#' @param protospacer_coords A list containing `protospacer_end` and `PAM_start` coordinates. Can be generated by `cut_site_protospacer_coordinates()`.
#' @param strand Character. The strand orientation, either `'+'` or `'-'`.
#'
#' @return A named list containing:
#' \describe{
#'   \item{start}{The absolute minimum genomic coordinate of the target site.}
#'   \item{stop}{The absolute maximum genomic coordinate of the target site.}
#' }
#'
#' @export
protospacer_coords_to_absolute_start_stop_coords <- function(
    protospacer_coords,
    strand
) {

  if (strand == '+') {
    # On the + strand, lowest coordinate is the 5' end of the spacer.
    start_pos <- protospacer_coords$protospacer_end

    stop_pos <- protospacer_coords$PAM_start

  } else if (strand == '-') {
    # On the - strand, lowest coordinate is the first base of the PAM (PAM_start).
    start_pos <- protospacer_coords$PAM_start

    # Highest coordinate is the 5' end of the spacer.
    stop_pos <- protospacer_coords$protospacer_end

  } else {
    stop("Strand must be either '+' or '-'.")
  }

  testthat::expect_true(start_pos < stop_pos)

  return(
    list(
      'start' = start_pos,
      'stop' = stop_pos
    )
  )
}
